# Generated by Django 5.0.6 on 2024-05-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100)),
                ('forma_pagamento', models.CharField(max_length=100)),
                ('parcelas', models.IntegerField()),
            ],
        ),
    ]
