# Generated by Django 5.0.6 on 2024-05-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='valor',
            field=models.CharField(max_length=100),
        ),
    ]
